In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [23]:
dict_homeprices = {'Area' : [2600, 3000, 3200, 3600,4000], 
                   'bedrooms' :[3,4,3.5,3,5], 
                   'age' :[20,15,18,30,8],
'Price' : [550000,565000,610000,595000,760000]}
df=pd.DataFrame(dict_homeprices)
df

Area  bedrooms  age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.5   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [26]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('Price',axis='columns'),df.Price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
reg.coef_

array([    198.47159002, -116583.73881651,  -14267.77585936])

In [22]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

Area bedrooms  age   Price
0  2600        3   20  550000
1  3000        4   15  565000
2  3200      NaN   18  610000
3  3600        3   30  595000
4  4000        5    8  760000

In [28]:
reg.intercept_

656046.5390048662

# Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old


In [31]:
reg.predict([[3000, 3, 40]])

array([330999.05823262])

In [32]:
198.47159002*3000 + -116583.73881651*3 + -14267.77585936*40 + 656046.5390048662

330999.05824093625

# Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [33]:
reg.predict([[2500, 4, 5]])

array([614551.67948517])

In [35]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [36]:
df = pd.read_csv(r"Downloads\life_expectancy_years.csv")
df

EmptyDataError: No columns to parse from file